/**
 * Registry of well-known local CLI tools: bin name → npm packages that
 * provide it. The first package is the canonical remediation suggestion;
 * the remaining packages are verified aliases for the same executable.
 * PS040 only reports commands it can map to a package —
 * unknown words are never flagged (precision over recall).
 */
const KNOWN_TOOL_PROVIDER_ALIASES: Readonly<Record<string, readonly string[]>> = {
  gatsby: ['gatsby'],
  'npm-run-all': ['npm-run-all2'],
  playwright: ['playwright'],
  'run-p': ['npm-run-all2'],
  'run-s': ['npm-run-all2'],
};

export const KNOWN_TOOLS: ReadonlyMap<string, readonly string[]> = new Map(
  Object.entries({
    tsc: 'typescript',
    tsserver: 'typescript',
    vitest: 'vitest',
    jest: 'jest',
    mocha: 'mocha',
    ava: 'ava',
    uvu: 'uvu',
    tap: 'tap',
    eslint: 'eslint',
    prettier: 'prettier',
    biome: '@biomejs/biome',
    stylelint: 'stylelint',
    tsx: 'tsx',
    'ts-node': 'ts-node',
    vite: 'vite',
    webpack: 'webpack',
    rollup: 'rollup',
    esbuild: 'esbuild',
    parcel: 'parcel',
    next: 'next',
    nuxt: 'nuxt',
    astro: 'astro',
    gatsby: 'gatsby-cli',
    remix: '@remix-run/dev',
    turbo: 'turbo',
    nx: 'nx',
    lerna: 'lerna',
    husky: 'husky',
    'lint-staged': 'lint-staged',
    concurrently: 'concurrently',
    'cross-env': 'cross-env',
    rimraf: 'rimraf',
    shx: 'shx',
    mkdirp: 'mkdirp',
    'cpy-cli': 'cpy-cli',
    cpy: 'cpy-cli',
    'http-server': 'http-server',
    serve: 'serve',
    nodemon: 'nodemon',
    pm2: 'pm2',
    standard: 'standard',
    'json-server': 'json-server',
    'dotenv-cli': 'dotenv-cli',
    'wait-on': 'wait-on',
    'npm-run-all': 'npm-run-all',
    'run-s': 'npm-run-all',
    'run-p': 'npm-run-all',
    onchange: 'onchange',
    playwright: '@playwright/test',
    cypress: 'cypress',
    wdio: '@wdio/cli',
    karma: 'karma',
    babel: '@babel/cli',
    madge: 'madge',
    'dependency-cruiser': 'dependency-cruiser',
    knip: 'knip',
    publint: 'publint',
    attw: '@arethetypeswrong/cli',
    oclif: 'oclif',
    vitepress: 'vitepress',
    typedoc: 'typedoc',
    'docsify-cli': 'docsify-cli',
    'gh-pages': 'gh-pages',
    'npm-check-updates': 'npm-check-updates',
    ncu: 'npm-check-updates',
    'pkg-pr-new': 'pkg-pr-new',
  }).map(
    ([bin, primaryProvider]) =>
      [bin, [primaryProvider, ...(KNOWN_TOOL_PROVIDER_ALIASES[bin] ?? [])]] as const,
  ),
);

/** Commands that ship with the OS or the Node/npm toolchain itself. */
export const SYSTEM_AND_TOOLCHAIN = new Set([
  // npm ecosystem runners (present when scripts run)
  'npm',
  'npx',
  'pnpm',
  'yarn',
  'yarnpkg',
  'bun',
  'bunx',
  'deno',
  'node',
  'corepack',
  // common OS-level commands available on all three OSes (or handled by other rules)
  'echo',
  'cd',
  'pwd',
  'exit',
  'true',
  'false',
  'git',
  'ssh',
  'scp',
  'curl',
  'docker',
  'make',
  'python',
  'python3',
  'pip',
  'go',
  'cargo',
  'ruby',
  'java',
  'mvn',
  'gradle',
  'dotnet',
]);
